### ISSUE TITLE
bhai real estate issue aa raha hai

### ISSUE THREAD

**Issue by abhay-0602** [ankit705yadav/Full-stack-real-estate#2]
Invalid `prisma.residency.create()` invocation:

{
  data: {
    title: 'Poonam Palace',
    description: 'Beautiful',
    price: 300000,
    address: 'colaba',
    country: 'India',
    city: 'mumbai',
    facilities: {
      bedrooms: 2,
      parkings: 2,
      bathrooms: 2
    },
    image: 'https://res.cloudinary.com/dggpr1aet/image/upload/v1707981031/r6poe6qxelncanupzxo4.jpg',
    owner: {
      connect: {
?       email?: String,
?       id?: String
      },
?     create?: UserCreateWithoutOwnedResidenciesInput | UserUncheckedCreateWithoutOwnedResidenciesInput,
?     connectOrCreate?: {
?       where: UserWhereUniqueInput,
?       create: UserCreateWithoutOwnedResidenciesInput | UserUncheckedCreateWithoutOwnedResidenciesInput
?     }
    }
  }
}

Argument data.owner.connect of type UserWhereUniqueInput needs at least one argument. Available args are listed in green.

Note: Lines with ? are optional.

    at file:///F:/Final%20project/server/controllers/resdCntrl.js:40:15Creating a user
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
Server is running on port 8000
{
  title: 'octal',
  description: 'fgdgg',
  price: 1000000,
  country: 'India',
  city: 'mumbai',
  address: 'vasai',
  image: 'https://res.cloudinary.com/dggpr1aet/image/upload/v1707981650/qlkyymlcsigkf5tzowkh.jpg',
  facilities: { bedrooms: 2, parkings: 2, bathrooms: 2 }
}
Error: 
Invalid `prisma.residency.create()` invocation:

{
  data: {
    title: 'octal',
    description: 'fgdgg',
    price: 1000000,
    address: 'vasai',
    country: 'India',
    city: 'mumbai',
    facilities: {
      bedrooms: 2,
      parkings: 2,
      bathrooms: 2
    },
    image: 'https://res.cloudinary.com/dggpr1aet/image/upload/v1707981650/qlkyymlcsigkf5tzowkh.jpg',
+   owner: {
+     create?: UserCreateWithoutOwnedResidenciesInput | UserUncheckedCreateWithoutOwnedResidenciesInput,
+     connectOrCreate?: UserCreateOrConnectWithoutOwnedResidenciesInput,
+     connect?: UserWhereUniqueInput
+   },
?   id?: String,
?   createdAt?: DateTime,
?   updatedAt?: DateTime
  }
}

Argument owner for data.owner is missing.

Note: Lines with + are required, lines with ? are optional.

    at file:///F:/Final%20project/server/controllers/resdCntrl.js:40:15

**Comment by abhay-0602** [comment]
Property add karte waqt
